// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DropZone: typeof import('./../src/components/DropZone.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Preview: typeof import('./../src/components/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spin: typeof import('./../src/components/Spin.vue')['default']
    Tast: typeof import('./../src/components/Tast.vue')['default']
    Toast: typeof import('./../src/components/Toast/Toast.vue')['default']
  }
}

export {}
